name: "Install yarn dependencies"
description: "Installs yarn dependencies and caches them."

outputs:
  cache_key:
    description: "The dependency cache key"
    value: ${{ steps.compute_lockfile_hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Compute dependency cache key
      id: compute_lockfile_hash
      run: node ./scripts/dependency-hash-key.js >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Check dependency cache
      uses: actions/cache@v4
      id: cache_dependencies
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ runner.os }}-dependency-cache-${{ steps.compute_lockfile_hash.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-dependency-cache-${{ steps.compute_lockfile_hash.outputs.hash }}
          ${{ runner.os }}-dependency-cache-
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: yarn install --ignore-engines --frozen-lockfile
