name: "Install yarn dependencies"
description: "Installs yarn dependencies and caches them."

inputs:
  save_cache:
    description: "If the dependency cache should be saved"

outputs:
  cache_key:
    description: "The dependency cache key"
    value: ${{ steps.compute_lockfile_hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Compute dependency cache key
      id: compute_lockfile_hash
      run: node ./scripts/dependency-hash-key.js >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Restore dependency cache from develop
      uses: actions/cache/restore@v4
      id: cache_dependencies
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ steps.compute_lockfile_hash.outputs.hash }}

    - name: Save dependency cache on develop
      uses: actions/cache/save@v4
      if: inputs.save_cache == 'true'
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ steps.compute_lockfile_hash.outputs.hash }}

    - name: Install dependencies
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: yarn install --ignore-engines --frozen-lockfile
      shell: bash

    - name: Upload dependency artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dependencies
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        retention-days: 2
        compression-level: 6
        overwrite: true
