name: "Install yarn dependencies"
description: "Installs yarn dependencies and caches them."

outputs:
  cache_key:
    description: "The dependency cache key"
    value: ${{ steps.compute_lockfile_hash.outputs.hash }}

runs:
  using: "composite"
  steps:
      # we use a hash of yarn.lock as our cache key, because if it hasn't changed, our dependencies haven't changed,
      # so no need to reinstall them
    - name: Compute dependency cache key
      id: compute_lockfile_hash
      run: echo "hash=${{ hashFiles('yarn.lock', 'packages/*/package.json', 'dev-packages/*/package.json') }}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Restore dependency cache
      uses: actions/cache/restore@v4
      with:
        enableCrossOsArchive: true
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: dependencies-${{ github.ref }}-${{ steps.compute_lockfile_hash.outputs.hash }}
        restore-keys: |
          dependencies-${{ github.ref }}-${{ steps.compute_lockfile_hash.outputs.hash }}
          dependencies-${{ github.ref }}
          dependencies

    # Only store cache on develop branch
    - name: Store cached dependencies
      uses: actions/cache/save@v4
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      with:
        enableCrossOsArchive: true
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: dependencies-${{ github.ref }}-${{ steps.compute_lockfile_hash.outputs.hash }}

    - name: Install dependencies
      run: yarn install --ignore-engines --frozen-lockfile
      shell: bash
