name: "Install Playwright dependencies"
description: "Installs Playwright dependencies and caches them."
inputs:
  browsers:
    description: 'What browsers to install.'
    default: 'chromium webkit firefox'

runs:
  using: "composite"
  steps:
      - name: Install Playwright dependencies
        run: npx playwright install ${{ inputs.browsers || 'chromium webkit firefox' }} --with-deps
        shell: bash
