name: "Install Playwright dependencies"
description: "Installs Playwright dependencies and caches them."

runs:
  using: "composite"
  steps:
      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(node -p "require('@playwright/test/package.json').version")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright dependencies (uncached)
        run: npx playwright install chromium webkit firefox --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Install Playwright system dependencies only (cached)
        run: npx playwright install-deps chromium webkit firefox
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        shell: bash
