minVersion: '0.23.1'
# changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: git-repository
    archive: /^sentry-deno-\d.*\.tgz$/
    repositoryUrl: git@github.com:getsentry/craft-test-repo.git
    stripComponents: 1
    branch: main
    createTag: true
