---
github:
  owner: getsentry
  repo: sentry-rrweb
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    tagPrefix: v
    access: public
