branches:
  only:
    - master

addons:
  chrome: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: true
sudo: required

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

language: node_js
dist: trusty

cache:
  directories:
  - node_modules

before_script: ./travis/before_script.sh

script: ./travis/script.sh

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      node_js: "8"
      script: ./travis/lint.sh

matrix:
  include:
    - env: NAME="raven-js"
      node_js: "8"
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script:
        - |
            if [[ ("$RAVEN_JS_CHANGES" = "true" || "$TRAVIS_PULL_REQUEST" = "false" ) ]]; then
            cd packages/raven-js
            npm install
            npm run test
            if [[ "$TRAVIS_SECURE_ENV_VARS" = "true" ]]; then
              npm run test:ci
            fi
            fi
