branches:
  only:
    - master

sudo: false
language: node_js
node_js:
- '8'
dist: trusty
cache:
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - env: NAME="raven-js"
      install: true
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script:
        - |
            cd packages/raven-js
            npm install
            npm run test
            if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
              npm run test:ci;
            else
              exit 0;
            fi
    - env: NAME="@sentry -> lint"
      script: yarn build && yarn lint
    - env: NAME="@sentry -> test"
      addons:
        chrome: stable
      script: yarn build && yarn test
