language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs"
before_install:
  - "npm install --upgrade npm -g"
matrix:
  allow_failures:
    - node_js: "0.6"
    - node_js: "iojs"
