branches:
  only:
    - master

sudo: required
language: node_js
dist: trusty
cache:
  directories:
  - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - |
      CHANGES=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master))
      if [ -n "$(grep 'raven-js' <<< "$CHANGES")" ]; then
      RAVEN_JS_CHANGES=true
      fi
      FORCE=$(git log --format=%B --no-merges -n 1)
      if [ -n "$(grep '\[force ci\]' <<< "$FORCE")" ]; then
      RAVEN_JS_CHANGES=true
      fi

matrix:
  include:
    - env: NAME="raven-js"
      node_js: "8"
      install: true
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script:
        - |
            cd packages/raven-js
            npm install
            npm run test
            if [[ ("$RAVEN_JS_CHANGES" = "true" || "$TRAVIS_PULL_REQUEST" = "false" ) && "$TRAVIS_SECURE_ENV_VARS" = "true" ]]; then
              npm run test:ci
            fi

    - env: NAME="raven-node"
      node_js:
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      install: true
      script:
        - |
            yarn
            yarn test-full

    - env: NAME="@sentry -> lint"
      node_js: "8"
      script: yarn build && yarn lint

    - env: NAME="@sentry -> test"
      node_js: "8"
      addons:
        chrome: stable
      script: yarn build && yarn test && yarn codecov
