branches:
  only:
    - master
sudo: false
language: node_js
node_js:
- '8'
dist: trusty
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  firefox: latest
  sauce_connect: true
script:
  - npm run test && if [ -z "$TRAVIS_SECURE_ENV_VARS" ]; then exit 0; else npm run test:ci; fi
