branches:
  only:
    - master

install: true
sudo: required

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

language: node_js
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

before_script: .travis/before_script.sh

script: .travis/script.sh

matrix:
  include:
    - node_js: "8"
      script: .travis/lint.sh
  exclude:
    - node_js: "8"
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script: .travis/script.sh
