branches:
  only:
    - master

sudo: false
language: node_js
node_js:
- '8'
dist: trusty
cache:
  directories:
  - node_modules


matrix:
  include:
    - env: NAME="raven-js"
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script:
        - npm run test && if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then npm run test:ci; else exit 0; fi
    - env: NAME="@sentry/browser"
      script:
      - cd packages/browser && yarn install && yarn test
    - env: NAME="@sentry/core"
      script:
      - cd packages/core && yarn install && yarn test
