branches:
  only:
    - master
    - /^release\/.+$/

install: true
sudo: required

language: node_js
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - name: '@sentry/packages - danger'
      node_js: '8'
      script: .travis/danger.sh
    - name: '@sentry/packages - lint'
      node_js: '8'
      script: .travis/lint.sh
    - name: '@sentry/packages - build and test [node v6]'
      node_js: '6'
      script: .travis/test.sh
    - name: '@sentry/packages - build and test [node v8]'
      node_js: '8'
      script: .travis/test.sh
    - name: '@sentry/packages - build and test [node v10]'
      node_js: '10'
      script: .travis/test.sh
    - name: '@sentry/browser - integration tests'
      node_js: '8'
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script: .travis/integration.sh
    - name: 'raven-js - unit and integration tests'
      node_js: '8'
      addons:
        chrome: stable
        firefox: latest
      script: .travis/raven-js.sh
    - name: 'raven-js - saucelabs tests'
      node_js: '8'
      addons:
        sauce_connect: true
      script: .travis/raven-js-saucelabs.sh
    - name: 'raven-node [node v4]'
      node_js: '4'
      script: .travis/raven-node.sh
    - name: 'raven-node [node v6]'
      node_js: '6'
      script: .travis/raven-node.sh
    - name: 'raven-node [node v8]'
      node_js: '8'
      script: .travis/raven-node.sh
    - name: 'raven-node [node v10]'
      node_js: '10'
      script: .travis/raven-node.sh

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/853ee4aa-d692-11e7-8c60-0a580a28020f/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
