branches:
  only:
    - master

sudo: false
language: node_js
node_js:
- '8'
dist: trusty
cache:
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - env: NAME="raven-js"
      install: true
      addons:
        chrome: stable
        firefox: latest
        sauce_connect: true
      script: .travis/raven-js.sh
    - env: NAME="@sentry/core"
      install: true
      script:
      - cd packages/core && yarn install && yarn test
    - env: NAME="@sentry/browser"
      install: true
      script:
      - yarn link
      - cd packages/core && yarn link && yarn install && yarn dist
      - cd ../browser
      - yarn link "@sentry/core"
      - yarn link "raven-js"
      - yarn install && yarn test
