version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-knex
    ports:
      - '5445:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tests
