name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: ['Type: Bug']
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
          required: true
        - label: I have reviewed the documentation https://docs.sentry.io/
          required: true
        - label: I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases
          required: true
  - type: dropdown
    id: type
    attributes:
      label: How do you use Sentry?
      options:
        - Sentry Saas (sentry.io)
        - Self-hosted/on-premise
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Which SDK are you using?
      description:
        If you're using the CDN bundles, please specify the exact bundle (e.g. `bundle.tracing.min.js`) in your SDK
        setup.
      options:
        - '@sentry/browser'
        - '@sentry/angular'
        - '@sentry/angular-ivy'
        - '@sentry/ember'
        - '@sentry/gatsby'
        - '@sentry/nextjs'
        - '@sentry/node'
        - '@sentry/opentelemetry-node'
        - '@sentry/react'
        - '@sentry/remix'
        - '@sentry/serverless'
        - '@sentry/svelte'
        - '@sentry/sveltekit'
        - '@sentry/vue'
        - '@sentry/wasm'
        - Sentry Browser Loader
        - Sentry Browser CDN bundle
    validations:
      required: true
  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the SDK are you using?
      placeholder: ex. 7.8.0
    validations:
      required: true
  - type: input
    id: framework-version
    attributes:
      label: Framework Version
      description:
        If you're using one of our framework-specific SDKs (`@sentry/react`, for example), what version of the
        _framework_ are you using?
      placeholder: ex. React 17.0.0
  - type: input
    id: link-to-sentry
    attributes:
      label: Link to Sentry event
      description:
        If applicable, please provide a link to the affected event from your Sentry account. The event will only be
        viewable by people working at Sentry.
      placeholder: https://<org-slug>.sentry.io/issues/<issue-id>/events/<event-id>/
  - type: textarea
    id: sdk-setup
    attributes:
      label: SDK Setup
      description:
        How do you set up your Sentry SDK? Please show us any pieces of code that seem relevant to you. (`Sentry.init()`
        options, build configurations, custom Sentry functions, ...)
      placeholder: |-
        For example:

        ```javascript
        Sentry.init({
          dsn: __YOUR_DSN__
          ...
        });
        ```
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: What can one do to get this error on their computer? The more specific you are the better!
      placeholder: |-
        1. What
        2. you
        3. did.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: If you have logs or screenshots, please include them in this field!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
