name: "Restore dependency & build cache"
description: "Restore the dependency & build cache."

runs:
  using: "composite"
  steps:
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check build cache
        uses: actions/cache/restore@v4
        id: build-cache
        with:
          enableCrossOsArchive: true
          path: ${{ env.CACHED_BUILD_PATHS }}
          key: ${{ env.BUILD_CACHE_KEY }}

      - name: Check if caches are restored
        uses: actions/github-script@v6
        if: steps.build-cache.outputs.cache-hit != 'true'
        with:
          script: core.setFailed('Dependency or build cache could not be restored - please re-run ALL jobs.')
