name: "Restore dependency & build cache"
description: "Restore the dependency & build cache."

runs:
  using: "composite"
  steps:
      - name: Check dependency cache
        id: dep-cache
        uses: actions/cache/restore@v4
        if: true == false
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ env.DEPENDENCY_CACHE_KEY }}

      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Install dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-engines --frozen-lockfile
        shell: bash
