name: 'Build & Test'
on:
  push:
    branches:
      - master
      - release/**
  pull_request:

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm

  job_size_check:
    name: Size Check
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/packages
      - uses: andresz1/size-limit-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: build

  job_lint:
    name: Lint
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/packages
      - name: Run Linter
        run: yarn lint

  job_danger:
    name: Danger
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/packages
      - name: Danger JS Action
        uses: danger/danger-js@9.1.8

  job_unit_test:
    name: Test
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/packages
      - name: Unit Tests
        run: yarn test
      - uses: codecov/codecov-action@v1

  job_browserstack_test:
    name: Browserstack
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/packages
      - name: Integration Tests
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          cd packages/browser
          yarn test:integration:checkbrowsers
          yarn test:integration
          yarn test:package

  job_zeus:
    name: Zeus
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/packages
      - name: Upload to Zeus
        env:
          ZEUS_API_TOKEN: ${{ secrets.ZEUS_API_TOKEN }}
          ZEUS_HOOK_BASE: ${{ secrets.ZEUS_HOOK_BASE }}
        run: |
          yarn global add @zeus-ci/cli
          zeus job update -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -r $GITHUB_SHA
          yarn lerna changed --include-merged-tags -p
          node scripts/package-and-upload-to-zeus.js
          zeus upload -t "application/javascript" ./packages/browser/build/bundle*
          zeus upload -t "application/javascript" ./packages/integrations/build/*
          zeus upload -t "application/javascript" ./packages/apm/build/*
          zeus upload -t "application/javascript" ./packages/tracing/build/*
          zeus job update --status=passed -b $GITHUB_RUN_ID -j $GITHUB_RUN_NUMBER -r $GITHUB_SHA
