
name: 'Build & Test'
on:
  push:
    branches:
      - develop
      - master
      - release/**
  pull_request:
  workflow_dispatch:
    inputs:
      commit:
        description: If the commit you want to test isn't the head of a branch, provide its SHA here
        required: false
  schedule:
    # Run every day at midnight (without cache)
    - cron: '0 0 * * *'

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  job_profiling_node_unit_tests:
    name: Profiling Node Unit Tests
    # needs: [job_get_metadata]
    # needs: [job_get_metadata, job_build]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out current commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.HEAD_COMMIT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v5
      - name: install dependencies
        run: |
          cd packages/profiling-node
          yarn install --ignore-scripts --frozen-lockfile
      - name: test https
        run: |
          cd packages/profiling-node
          yarn test:https
      - name: configure node-gyp
        run: |
          cd packages/profiling-node
          npm build:bindings:configure
      - name: build lib and bindings
        run: |
          cd packages/profiling-node
          yarn build
      - name: unit test
        run: |
          cd packages/profiling-node
          yarn test
