
name: 'Build & Test Profiling Node'
on:
  push:
    branches:
      - develop
      - master
      - release/**
  pull_request:
  workflow_dispatch:
    inputs:
      commit:
        description: If the commit you want to test isn't the head of a branch, provide its SHA here
        required: false
  schedule:
    # Run every day at midnight (without cache)
    - cron: '0 0 * * *'

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  profiling_node_separate:
    name: Profiling Node Unit Tests
    # needs: [job_get_metadata]
    # needs: [job_get_metadata, job_build]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out current commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.HEAD_COMMIT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          cd packages/profiling-node
          yarn install --ignore-scripts --frozen-lockfile
      - name: Configure node-gyp
        run: |
          cd packages/profiling-node
          yarn build:bindings:configure
      - name: Build Dependencies
        run: yarn build
      - name: Unit Test
        run: |
          cd packages/profiling-node
          yarn test
