name: Test
on:
  push:
    branches:
      - master
      - release/**
      - major/**
  pull_request:

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10, 12, 14]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        env:
          NODE_VERSION: ${{ matrix.node }}
        run: |
          ./scripts/test.sh
