name: Test
on:
  push:
    branches:
      - master
      - release/**
      - major/**
  pull_request:

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10, 12, 14]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/**/node_modules
            ${{ github.workspace }}/packages/**/build
            ${{ github.workspace }}/packages/**/dist
            ${{ github.workspace }}/packages/**/esm
            ${{ github.workspace }}/packages/serverless/dist-awslambda-layer/*.zip
          key: ${{ github.sha }}

      - name: Test
        env:
          NODE_VERSION: ${{ matrix.node }}
        run: |
          ./scripts/test.sh
