name: Gitflow - Sync develop into master
on:
  pull_request:
    - types: [closed]
    - branches:
        - 'develop'

env:
  MAIN_BRANCH: master

jobs:
  main:
    name: Create PR develop->master
    runs-on: ubuntu-20.04
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'meta(changelog):')
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ env.MAIN_BRANCH }}
          pr_title: '[Gitflow] Merge ${{ github.ref_name }} into ${{ env.MAIN_BRANCH }}'
          pr_body: 'Merge ${{ github.ref_name }} branch into ${{ env.MAIN_BRANCH }}'
          pr_label: 'Dev: Gitflow'
          # This token is scoped to Daniel Griesser
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: Enable automerge for PR
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge

      # https://github.com/marketplace/actions/auto-approve
      - name: Auto approve PR
        # Always skip this for now, until we got a proper bot setup
        if: steps.open-pr.outputs.pr_number != ''
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          review-message: 'Auto approved automated PR'

  skipped:
    runs-on: ubuntu-20.04
    if: |
      github.event.pull_request.merged == false ||
      startsWith(github.event.pull_request.title, 'meta(changelog):') == false
    steps:
      - name: Sync skipped
        run: echo "OK"
