name: "Automation: Notify issues for release"
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: Which version to notify issues for
        required: false

  # WIP just for debugging this...
  push:

# This workflow is triggered when a release is published
jobs:
  release-comment-issues:
    runs-on: ubuntu-20.04
    name: 'Notify issues'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Compute dependency cache key
        id: compute_lockfile_hash
        run: node ./scripts/dependency-hash-key.js >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Check dependency cache
        uses: actions/cache/restore@v4
        id: cache_dependencies
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/packages/*/node_modules
            ${{ github.workspace }}/dev-packages/*/node_modules
            ~/.cache/mongodb-binaries/
          key: ${{ steps.compute_lockfile_hash.outputs.hash }}

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: yarn install --ignore-engines --frozen-lockfile
        shell: bash

      - name: Get version
        id: get_version
        run: echo "version=${{ github.event.inputs.version || github.event.release.tag_name || '8.32.0' }}" >> $GITHUB_OUTPUT

      - name: Comment on linked issues that are mentioned in release
        if: steps.get_version.outputs.version != ''
        uses: ./dev-packages/release-comment-issues-gh-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.version }}
