name: 'Bundle Size'
on:
  pull_request:
    branches:
      - master
jobs:
  job_1:
    name: Size Check
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
